apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "aqakscluster-46f2"
    labels:
        app: "aqakscluster-46f2"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: hackapi-aqakscluster-46f2.4a680e702b4f4f89ac6e.canadacentral.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "aqakscluster-46f2"
                servicePort: 80