apiVersion: v1
kind: Service
metadata:
    name: "poi"
    labels:
        app: "poi"
spec:
    type: ClusterIP
    ports:
    - port: 81
      targetPort: 81
      protocol: TCP
      name: http
    selector:
        app: "poi"