apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deploy
  namespace: hackweb
  labels:
    deploy: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - image: "aqaksacr.azurecr.io/tripviewer"
        imagePullPolicy: Always
        name: tripviewer
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
        env:
          - name: USERPROFILE_API_ENDPOINT
            value: "http://userprofile.hackweb.svc.cluster.local"
          - name: TRIPS_API_ENDPOINT
            value: "http://trips.hackweb.svc.cluster.local"
          - name: BING_MAPS_KEY
            value: ""