apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tripviewer"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "tripviewer"
  template:
    metadata:
      labels:
        app: "tripviewer"
    spec:
      containers:
        - name: "tripviewer"
          image: "aqaksacr.azurecr.io/tripviewer"
          ports:
          - containerPort: 80