on: [push]
jobs:
  build-and-deploy-poi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aqaksacr.azurecr.io
        username: ${{ secrets.acr_aqaksacr_username }}
        password: ${{ secrets.acr_aqaksacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/poi" -f  "poi/Dockerfile" -t aqaksacr.azurecr.io/poi:${{ github.sha }} --label dockerfile-path=poi/Dockerfile
        docker push aqaksacr.azurecr.io/poi:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aqakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hackapi | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hackapi`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hackapi
        container-registry-url: aqaksacr.azurecr.io
        container-registry-username: ${{ secrets.acr_aqaksacr_username }}
        container-registry-password: ${{ secrets.acr_aqaksacr_password }}
        secret-name: aqaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: hackapi
        manifests: |
          manifests/poi-deployment.yml
          manifests/poi-service.yml
          manifests/poi-ingress.yml
        images: |
          aqaksacr.azurecr.io/poi:${{ github.sha }}
        imagepullsecrets: |
          aqaksclusterdockerauth


  build-and-deploy-tripviewer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aqaksacr.azurecr.io
        username: ${{ secrets.acr_aqaksacr_username }}
        password: ${{ secrets.acr_aqaksacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/tripviewer" -f  "tripviewer/Dockerfile" -t aqaksacr.azurecr.io/tripviewer:${{ github.sha }} --label dockerfile-path=tripviewer/Dockerfile
        docker push aqaksacr.azurecr.io/tripviewer:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aqakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep hackweb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace hackweb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: hackweb
        container-registry-url: aqaksacr.azurecr.io
        container-registry-username: ${{ secrets.acr_aqaksacr_username }}
        container-registry-password: ${{ secrets.acr_aqaksacr_password }}
        secret-name: aqaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: hackweb
        manifests: |
          manifests/tripviewer-deployment.yml
          manifests/tripviewer-service.yml
          manifests/tripviewer-ingress.yml
        images: |
          aqaksacr.azurecr.io/tripviewer:${{ github.sha }}
        imagepullsecrets: |
          aqaksclusterdockerauth


  